### ISSUE TITLE
A test filename cannot contain "patch"

### ISSUE THREAD

**Issue by aschlicht** [ThrowTheSwitch/Ceedling#116] opened 2017-01-20 19:25 UTC
I know I don't have the very latest version (0.25) of Ceedling. Thought I'd report the issue anyway. I found the problem because I have a MessageDispatcher.h, MessageDispatcher.c and a unit test file called test_MessageDispatcher.c. I narrowed it down to the word Dispatch. The attached zip file contains Dispatch.h, Dispatch.c, test_Dispatch.c and a couple output files. Everything works fine if I rename test_Dispatch.c to test_Dispach.c. Dispatch.h and Dispatch.c can keep the same name and do not need to be renamed to Dispach.h and Dispach.c. The problem is with the name, not contents, of the test .c file. Not a high priority because there is an easy workaround; however, sometimes you find other bugs when resolving anomalies.

[Dispatch.zip](https://github.com/ThrowTheSwitch/Ceedling/files/720276/Dispatch.zip)

Operating System: Windows 10
Compiler: gcc version 6.2.0 (i686-win32-sjlj-rev1, Built by MinGW-W64 project)
Ruby: ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
  Ceedling:: 0.24.0
CException:: 1.3.1.18
     CMock:: 2.4.3.215
     Unity:: 2.4.0.120

**Comment by mvandervoord** [comment] 2017-01-20 19:37
Hey, thanks for the detailed information! It's so nice to have someone take the time to put together a good reproducible report. I'll check into this!

**Comment by aschlicht** [comment] 2017-01-20 20:56
You're welcome! Thank you for making such a great unit test framework for C. It's almost as easy as writing unit tests for C#. I love how easy it is to mock function calls when testing higher level code. Keeps it a unit test and not an integration test.

**Comment by dpostorivo** [comment] 2017-01-24 03:45
I actually have a note in one of my test files from a previous coworker that sheds a little more light on what's going on:

```
 * \note  This file was renamed (from test_CommandDispatcher.c)
 *        in order to work-around Windows Installer Detection Technology
 *        (part of UAC), which requires admin privileges for files with
 *        "patch" occurring anywhere in the executable filename.
```
I've personally never noticed this issue as I only use ceedling on linux and osx and I have other test files in other projects name test_XDispatcher.c without these problems on those OSes. I'm not sure how easy this will be to fix.

**Comment by aschlicht** [comment] 2017-01-29 22:35
Thank you for looking into the issue. Looks like a strange and hard to solve issue on Windows. I wouldn't worry about spending too much time to resolve it since there is an easy workaround.

**Comment by mvandervoord** [comment] 2017-03-13 20:38
I think I'm just going to close this one, since there is no simple solution. I've added a note to the documentation to help our future selves.

**Closed by mvandervoord** 2017-03-13 20:38 UTC

**Comment by rasup** [comment] 2017-07-07 10:30
See [here ](https://github.com/ThrowTheSwitch/Ceedling/issues/146#issuecomment-313640036) for how to solve this problem. Another way to solve it is to insert a manifest file into the affected executable, see [here ](https://github.com/bmatzelle/gow/issues/156) for an explanation.
