### ISSUE TITLE
ceedling exit code is 0 on unit test failure

### ISSUE THREAD

**Issue by gpenghe** [ThrowTheSwitch/Ceedling#538] opened 2020-12-02 21:24 UTC
Let's re-open the closed issue of #174. It's still there.

**Comment by art-of-dom** [comment] 2020-12-09 23:37
So I worked on this issue years ago and I'm just jumping back into contributing to this repo now so it may take a bit for me to diagnose. I did think there were system tests to prevent this regression though so I'll need to see what's changed under the hood. 

I suggest using the old style `rake test:all` with the rakefile.rb to see if that unblocks you in the mean time. I've honestly never switched since I have other tools using rake too so I know that's working for rake as of ceedling 0.30.0.

**Comment by joustava** [comment] 2020-12-16 20:18
Where can the old style rakefile.rb content be found?

**Comment by art-of-dom** [comment] 2020-12-26 20:30
Sorry for the delay. This is the rakefile.rb for Ceedling as a gem:

```
require 'ceedling'

Ceedling.load_project
```
I can dig up a local version of the rakefile if needed.

**Comment by mkarlesky** [comment] 2024-03-06 16:06
I'm closing this PR as the issue has been resolved for a while and certainly is handled properly in 0.32. See comments in now closed #644.

Briefly, Ceedling now distinguishes test failures from build errors. In default usage, test failures are equivalent to build errors, emitting an exit code of 1 in either case. A configuration file option `:graceful_fail` changes the default behavior such that an error-free build with test failures will emit an exit code of 0.

**Closed by mkarlesky** 2024-03-06 16:06 UTC
