### ISSUE TITLE
Mock Won't Compile When Using Custom Type

### ISSUE THREAD

**Issue by randomThv** [ThrowTheSwitch/Ceedling#470] opened 2020-03-04 18:30 UTC
I have been trying to run a CMock _ExpectAndReturn() test on a function that accepts a pointer to a custom struct that I have defined. In a nutshell, even when I am clearly setting the members of the struct correctly, the test fails because of an unexpected argument type, and neither the values for that argument (both expected and actual) that are printed out are what I have set them to in the test and code-under-test. I have defined the struct in the test as a global variable to eliminate possible scope-expiration problems, but that did not change the outcome of the test.

Here is the struct definition. `StateMachine_EventID_t` is an enumerated type.
```
typedef struct
{
    StateMachine_EventID_t id;
    void *data_ptr;
} StateMachine_Event_t;
```

And here is the prototype for the function I am trying to mock:
```
StateMachine_return_t stateMachine_generateEvent(StateMachine_Event_t *event);
```

My current thought is that I need to define `StateMachine_Event_t`, so that Unity can compare the actual members of the struct instead of just doing a memory comparison. I created a Unity helper file, shown here.

unity_helper.h
```
#ifndef _UNITY_HELPER
#define _UNITY_HELPER

#define UNITY_TEST_ASSERT_EQUAL_StateMachine_Event_t(expected, actual, line, message)

#endif // _UNITY_HELPER
```

unity_helper.c
```
#include "StateMachine_events_definitions.h"
#include "unity.h"

void AssertEqualStateMachine_Event_t(StateMachine_Event_t expected, StateMachine_Event_t actual, unsigned short line)
{
	UNITY_TEST_ASSERT_EQUAL_INT(expected.id, actual.id, line, "StateMachine_Event_t.id enum failed");
	UNITY_TEST_ASSERT_EQUAL_MEMORY(expected.data_ptr, actual.data_ptr, 1, line, "StateMachine_Event_t.data_ptr memory failed");
}
```

After I added the necessary lines in the project.yml file to include the Unity helper files, I run Ceedling and it generates a mock file (copied at the end of this post), showing that it must recognize the StateMachine_Event_t type that I have defined for it. However, compilation of the then fails with the following error message:
```
Compiling mock_StateMachine_events.c...

      if (*cmock_call_instance->Expected_event != *event) {
          ^
"C:\Users\A6778\Documents\SVN\embedded\projects\datalogger\gen6\trunk\build\test\mocks\mock_StateMachine_events.c",115  Error[Pe041]:
          expression must have arithmetic or pointer type

      if (*cmock_call_instance->Expected_event != *event) {
          ^
"C:\Users\A6778\Documents\SVN\embedded\projects\datalogger\gen6\trunk\build\test\mocks\mock_StateMachine_events.c",242  Error[Pe041]:
          expression must have arithmetic or pointer type
ERROR: Shell command failed.
```

Evidently it doesn't like the dereferencing that is going on here, but from what I can see in the mock file, that value should be a pointer. Any suggestions on what might be causing this to occur? I put a comment indicating the line in the following mock file that is causing the error.

```
/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_StateMachine_events.h"
#include "../../../test/unity_helper.h"

static const char* CMockString_event = "event";
static const char* CMockString_stateMachine_generateEvent = "stateMachine_generateEvent";
static const char* CMockString_stateMachine_waitAndReceiveEvent = "stateMachine_waitAndReceiveEvent";

typedef struct _CMOCK_stateMachine_generateEvent_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  StateMachine_return_t ReturnVal;
  int CallOrder;
  StateMachine_Event_t* Expected_event;
  int Expected_event_Depth;
  int ReturnThruPtr_event_Used;
  StateMachine_Event_t* ReturnThruPtr_event_Val;
  int ReturnThruPtr_event_Size;
  int IgnoreArg_event;

} CMOCK_stateMachine_generateEvent_CALL_INSTANCE;

typedef struct _CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ExpectAnyArgsBool;
  StateMachine_return_t ReturnVal;
  int CallOrder;
  StateMachine_Event_t* Expected_event;
  int Expected_event_Depth;
  int ReturnThruPtr_event_Used;
  StateMachine_Event_t* ReturnThruPtr_event_Val;
  int ReturnThruPtr_event_Size;
  int IgnoreArg_event;

} CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE;

static struct mock_StateMachine_eventsInstance
{
  int stateMachine_generateEvent_IgnoreBool;
  StateMachine_return_t stateMachine_generateEvent_FinalReturn;
  CMOCK_MEM_INDEX_TYPE stateMachine_generateEvent_CallInstance;
  int stateMachine_waitAndReceiveEvent_IgnoreBool;
  StateMachine_return_t stateMachine_waitAndReceiveEvent_FinalReturn;
  CMOCK_MEM_INDEX_TYPE stateMachine_waitAndReceiveEvent_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_StateMachine_events_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.stateMachine_generateEvent_CallInstance;
  if (Mock.stateMachine_generateEvent_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_stateMachine_generateEvent);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
  call_instance = Mock.stateMachine_waitAndReceiveEvent_CallInstance;
  if (Mock.stateMachine_waitAndReceiveEvent_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_stateMachine_waitAndReceiveEvent);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == call_instance, cmock_line, CMockStringCalledLess);
  UNITY_CLR_DETAILS();
}

void mock_StateMachine_events_Init(void)
{
  mock_StateMachine_events_Destroy();
}

void mock_StateMachine_events_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

StateMachine_return_t stateMachine_generateEvent(StateMachine_Event_t* event)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_stateMachine_generateEvent);
  cmock_call_instance = (CMOCK_stateMachine_generateEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.stateMachine_generateEvent_CallInstance);
  Mock.stateMachine_generateEvent_CallInstance = CMock_Guts_MemNext(Mock.stateMachine_generateEvent_CallInstance);
  if (Mock.stateMachine_generateEvent_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.stateMachine_generateEvent_FinalReturn;
    memcpy((void*)(&Mock.stateMachine_generateEvent_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(StateMachine_return_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(StateMachine_return_t) ? 1 : -1])); /* add StateMachine_return_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_event)
  {
    UNITY_SET_DETAILS(CMockString_stateMachine_generateEvent,CMockString_event);
    if (*cmock_call_instance->Expected_event != *event) { // <-----------------This is the line throwing the error
    UNITY_TEST_ASSERT_EQUAL_StateMachine_Event_t(*cmock_call_instance->Expected_event, *event, cmock_line, CMockStringMismatch);
    }
  }
  }
  if (cmock_call_instance->ReturnThruPtr_event_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(event, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)event, (void*)cmock_call_instance->ReturnThruPtr_event_Val,
      cmock_call_instance->ReturnThruPtr_event_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_stateMachine_generateEvent(CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance, StateMachine_Event_t* event, int event_Depth);
void CMockExpectParameters_stateMachine_generateEvent(CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance, StateMachine_Event_t* event, int event_Depth)
{
  cmock_call_instance->Expected_event = event;
  cmock_call_instance->Expected_event_Depth = event_Depth;
  cmock_call_instance->IgnoreArg_event = 0;
  cmock_call_instance->ReturnThruPtr_event_Used = 0;
}

void stateMachine_generateEvent_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, StateMachine_return_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stateMachine_generateEvent_CALL_INSTANCE));
  CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_generateEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stateMachine_generateEvent_CallInstance = CMock_Guts_MemChain(Mock.stateMachine_generateEvent_CallInstance, cmock_guts_index);
  Mock.stateMachine_generateEvent_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.stateMachine_generateEvent_IgnoreBool = (int)1;
}

void stateMachine_generateEvent_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, StateMachine_return_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stateMachine_generateEvent_CALL_INSTANCE));
  CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_generateEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stateMachine_generateEvent_CallInstance = CMock_Guts_MemChain(Mock.stateMachine_generateEvent_CallInstance, cmock_guts_index);
  Mock.stateMachine_generateEvent_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (int)1;
}

void stateMachine_generateEvent_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, StateMachine_Event_t* event, StateMachine_return_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stateMachine_generateEvent_CALL_INSTANCE));
  CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_generateEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stateMachine_generateEvent_CallInstance = CMock_Guts_MemChain(Mock.stateMachine_generateEvent_CallInstance, cmock_guts_index);
  Mock.stateMachine_generateEvent_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_stateMachine_generateEvent(cmock_call_instance, event, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(StateMachine_return_t[sizeof(cmock_to_return) == sizeof(StateMachine_return_t) ? 1 : -1])); /* add StateMachine_return_t to :treat_as_array if this causes an error */
}

void stateMachine_generateEvent_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, StateMachine_Event_t* event, int event_Depth, StateMachine_return_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stateMachine_generateEvent_CALL_INSTANCE));
  CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_generateEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stateMachine_generateEvent_CallInstance = CMock_Guts_MemChain(Mock.stateMachine_generateEvent_CallInstance, cmock_guts_index);
  Mock.stateMachine_generateEvent_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_stateMachine_generateEvent(cmock_call_instance, event, event_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void stateMachine_generateEvent_CMockReturnMemThruPtr_event(UNITY_LINE_TYPE cmock_line, StateMachine_Event_t* event, int cmock_size)
{
  CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_generateEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.stateMachine_generateEvent_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_event_Used = 1;
  cmock_call_instance->ReturnThruPtr_event_Val = event;
  cmock_call_instance->ReturnThruPtr_event_Size = cmock_size;
}

void stateMachine_generateEvent_CMockIgnoreArg_event(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_stateMachine_generateEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_generateEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.stateMachine_generateEvent_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_event = 1;
}

StateMachine_return_t stateMachine_waitAndReceiveEvent(StateMachine_Event_t* event)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_stateMachine_waitAndReceiveEvent);
  cmock_call_instance = (CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.stateMachine_waitAndReceiveEvent_CallInstance);
  Mock.stateMachine_waitAndReceiveEvent_CallInstance = CMock_Guts_MemNext(Mock.stateMachine_waitAndReceiveEvent_CallInstance);
  if (Mock.stateMachine_waitAndReceiveEvent_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.stateMachine_waitAndReceiveEvent_FinalReturn;
    memcpy((void*)(&Mock.stateMachine_waitAndReceiveEvent_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(StateMachine_return_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(StateMachine_return_t) ? 1 : -1])); /* add StateMachine_return_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_event)
  {
    UNITY_SET_DETAILS(CMockString_stateMachine_waitAndReceiveEvent,CMockString_event);
    if (*cmock_call_instance->Expected_event != *event) {
    UNITY_TEST_ASSERT_EQUAL_StateMachine_Event_t(*cmock_call_instance->Expected_event, *event, cmock_line, CMockStringMismatch);
    }
  }
  }
  if (cmock_call_instance->ReturnThruPtr_event_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(event, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)event, (void*)cmock_call_instance->ReturnThruPtr_event_Val,
      cmock_call_instance->ReturnThruPtr_event_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_stateMachine_waitAndReceiveEvent(CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance, StateMachine_Event_t* event, int event_Depth);
void CMockExpectParameters_stateMachine_waitAndReceiveEvent(CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance, StateMachine_Event_t* event, int event_Depth)
{
  cmock_call_instance->Expected_event = event;
  cmock_call_instance->Expected_event_Depth = event_Depth;
  cmock_call_instance->IgnoreArg_event = 0;
  cmock_call_instance->ReturnThruPtr_event_Used = 0;
}

void stateMachine_waitAndReceiveEvent_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, StateMachine_return_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE));
  CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stateMachine_waitAndReceiveEvent_CallInstance = CMock_Guts_MemChain(Mock.stateMachine_waitAndReceiveEvent_CallInstance, cmock_guts_index);
  Mock.stateMachine_waitAndReceiveEvent_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.stateMachine_waitAndReceiveEvent_IgnoreBool = (int)1;
}

void stateMachine_waitAndReceiveEvent_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, StateMachine_return_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE));
  CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stateMachine_waitAndReceiveEvent_CallInstance = CMock_Guts_MemChain(Mock.stateMachine_waitAndReceiveEvent_CallInstance, cmock_guts_index);
  Mock.stateMachine_waitAndReceiveEvent_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (int)1;
}

void stateMachine_waitAndReceiveEvent_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, StateMachine_Event_t* event, StateMachine_return_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE));
  CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stateMachine_waitAndReceiveEvent_CallInstance = CMock_Guts_MemChain(Mock.stateMachine_waitAndReceiveEvent_CallInstance, cmock_guts_index);
  Mock.stateMachine_waitAndReceiveEvent_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_stateMachine_waitAndReceiveEvent(cmock_call_instance, event, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(StateMachine_return_t[sizeof(cmock_to_return) == sizeof(StateMachine_return_t) ? 1 : -1])); /* add StateMachine_return_t to :treat_as_array if this causes an error */
}

void stateMachine_waitAndReceiveEvent_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, StateMachine_Event_t* event, int event_Depth, StateMachine_return_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE));
  CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stateMachine_waitAndReceiveEvent_CallInstance = CMock_Guts_MemChain(Mock.stateMachine_waitAndReceiveEvent_CallInstance, cmock_guts_index);
  Mock.stateMachine_waitAndReceiveEvent_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (int)0;
  CMockExpectParameters_stateMachine_waitAndReceiveEvent(cmock_call_instance, event, event_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void stateMachine_waitAndReceiveEvent_CMockReturnMemThruPtr_event(UNITY_LINE_TYPE cmock_line, StateMachine_Event_t* event, int cmock_size)
{
  CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.stateMachine_waitAndReceiveEvent_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_event_Used = 1;
  cmock_call_instance->ReturnThruPtr_event_Val = event;
  cmock_call_instance->ReturnThruPtr_event_Size = cmock_size;
}

void stateMachine_waitAndReceiveEvent_CMockIgnoreArg_event(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE* cmock_call_instance = (CMOCK_stateMachine_waitAndReceiveEvent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.stateMachine_waitAndReceiveEvent_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_event = 1;
}
```

**Comment by CezaryGapinski** [comment] 2020-03-09 14:41
I have the same in latest release Ceedling version 0.29.1, but now I can't find it in the current master branch on GitHub repository. The problem is related to CMock not to the Ceedling. I think it is fixed in this [commit](https://github.com/ThrowTheSwitch/CMock/commit/03ddcb9bade7021181b7d5a7ee14e94a05238636), but this fix showed up after the latest Ceedling release.

You can use develop version of Ceedling with new CMock, or you have to wait till the next Ceedling release (I do not know when the new version will be released).

**Comment by randomThv** [comment] 2020-03-10 16:11
Thanks for the info! That helps immensely.

**Closed** 2020-03-10 16:12 UTC
