### ISSUE TITLE
Ceedling Unity Defines Not Being Used

### ISSUE THREAD

**Issue by cwilliamson-bti** [ThrowTheSwitch/Ceedling#851] opened 2024-02-23 23:14 UTC
Hi,

When using the "unity" section in the project.yml to set defines for compiling Unity I'm not getting the correct build for Unity.
For example, if I set the "UNITY_COMPARE_PTRS_ON_ZERO_ARRAY" in the unity section like below:
```
:unity:
  :defines:
    - UNITY_COMPARE_PTRS_ON_ZERO_ARRAY 
    - UNITY_EXCLUDE_FLOAT
```
I still get the ""You Asked Me To Compare Nothing, Which Was Pointless..." error when testing comparing a pointer with a zero length.

If I move the define the "common" defines section shown below, unity correctly compares the pointer if zero is passed as the length.
```
:defines:
  :common: &common_defines 
    - UNITY_COMPARE_PTRS_ON_ZERO_ARRAY 
```

Before building I've "clobbered" to get a fresh build but the problem isn't solved.
I'm using ceedling 0.32.0 on Windows.

**Comment by mkarlesky** [comment] 2024-02-24 18:20
Hi, @cwilliamson-bti. So sorry for this trouble. Since 0.32 is still in pre-release could you provide the specific build you downloaded? There was a period in the pre-release history where `:unity` ↳ `:defines` were processed differently than they had been previously. That change was reverted in more recent pre-release versions. Alternatively, you could just try the most recent pre-release build of 0.32.

**Comment by mkarlesky** [comment] 2024-06-26 02:12
I can confirm that this bug has been fixed in pre-release versions of Ceedling since this issue was opened.

**Closed by mkarlesky** 2024-06-26 02:12 UTC
