### ISSUE TITLE
:flags: seem to not be passed correctly

### ISSUE THREAD

**Issue by bu5hm4nn** [ThrowTheSwitch/Ceedling#43] opened 2014-10-13 07:50 UTC
I am using Ceedling with MingGW GCC and I would like to tell GCC to use c99. Since gcc is already the default, I did not add any `:tools:` section. So according to the documentation I added a `:flags:` section in my project.yml:
```
:flags:
  :test:
    :compile:
      :*:
        - -std=c99
```
But I still get the GCC errors telling me I am not using c99 and running `rake test:all --trace` reveals that the flags are not being appended to the commandline.

**Comment by kyork-cl** [comment] 2015-07-06 16:16
I had a similar issue related to the `:link:` settings.  I was able to fix it by adjusting the defaults.rb file

        diff --git a/vendor/ceedling/lib/ceedling/defaults.rb b/vendor/ceedling/lib/ceedling/defaults.rb
        index 0394c2b..3c78500 100644
        --- a/vendor/ceedling/lib/ceedling/defaults.rb
        +++ b/vendor/ceedling/lib/ceedling/defaults.rb
        @@ -30,6 +30,7 @@ DEFAULT_TEST_LINKER_TOOL = {
           :arguments => [
             "\"${1}\"".freeze,
             "-o \"${2}\"".freeze,
        +    "\"${4}\"".freeze,
             ].freeze
           }

It looks like you can make a similar modification to the `DEFAULT_TEST_COMPILER_TOOL` value to fix the compiler problem as well.

**Comment by kotmage** [comment] 2015-11-25 04:12
Ping! Still a problem: i suggest a bit different approach btw:
:arguments => [
    +   "${4}".freeze,
         "\"${1}\"".freeze,
         "-o \"${2}\"".freeze,
         ].freeze

**Comment by mradecki** [comment] 2015-11-26 13:43
Yeah. Doesn't work for me either.

**Comment by recursify** [comment] 2016-02-03 23:46
Yep, doesn't work for me either.  I'll see if I can dig into ceedling and see what's going on, perhaps later this week.

**Comment by mvandervoord** [comment] 2016-02-04 01:20
There is a branch bug/nonportable which attempts to fix this and a few other issues. It's not fully tested yet, but you're welcome to grab it and see if it addresses your problem.

**Comment by pfaco** [comment] 2016-02-04 23:46
So, for clarification: there's no way, right now, to use Ceedling in C99 mode?

**Comment by mvandervoord** [comment] 2016-02-05 01:31
I believe there is. I think the branch mentioned above fixes it. I just don't have all the self-tests finished to prove it yet. :)

**Comment by pfaco** [comment] 2016-02-05 01:42
any idea when this branch will be stable?
can I get this branch in anyway like I did to get ceedling? ("gem install ceedling")

**Comment by michkot** [comment] 2016-02-05 09:48
@pfaco one way is to fix the defaults.rb file manually as described above, e.g. added one line to it.

**Comment by mvandervoord** [comment] 2016-02-05 16:12
whew. Ok. I think I have this issue fixed and merged into the main branch. If you have it installed already,  you can update by typing `gem update ceedling`, otherwise use `gem install ceedling`. This will pull down the latest gem.

If you started a project already using `ceedling new projname --as-gem` then I think you are ready to go. 

Otherwise, ceedling is probably still going to report as 0.18 instead of the new 0.19 when you type `rake version`. If this is the case, I think the only option at the moment is to manually replace the vendor directory. We're going to make this easier in the future.

I'd appreciate anyone who can let me know if this update works for them (either way)

**Comment by recursify** [comment] 2016-02-05 22:05
Thanks @mvandervoord , seems to be working for me with the below config!  Note the `-Wno-tautological-pointer-compare` I had to add for Cmock to work.  Not a big deal in my case, but worth noting.

```
:flags:
  :test:
    :compile:
      :*:
        - -Wall
        - -Wno-tautological-pointer-compare # Cmock may create these, so ignore
	- -Wno-missing-braces
        - -Werror
```

**Comment by mvandervoord** [comment] 2016-02-05 22:28
Awesome.

Thanks for letting me know that it's working, and about the CMock error. I'm pretty sure issue is already on the CMock buglist, but I'll double check. 

I'm going to close this issue now. If anyone sees anything else quirky related to this, let me know.

**Closed by mvandervoord** 2016-02-05 22:28 UTC

**Comment by swaldhoer** [comment] 2023-03-28 08:02
> Thanks @mvandervoord , seems to be working for me with the below config!  Note the `-Wno-tautological-pointer-compare` I had to add for Cmock to work.  Not a big deal in my case, but worth noting.
> 
> ```
> :flags:
>   :test:
>     :compile:
>       :*:
>         - -Wall
>         - -Wno-tautological-pointer-compare # Cmock may create these, so ignore
>         - -Werror
> ```
> 

Should this work on Windows too?
Because I did not get this working

**Comment by mvandervoord** [comment] 2023-03-28 11:56
@swaldhoer The bug above was for windows using mingw. If you're having a problem, you're going to need to be more specific. What error are you getting? what compiler version? what version of cmock? how are you building it? etc.

**Comment by swaldhoer** [comment] 2023-03-28 15:56
> @swaldhoer The bug above was for windows using mingw. If you're having a problem, you're going to need to be more specific. What error are you getting? what compiler version? what version of cmock? how are you building it? etc.
> 

Yes, mingw64 on Windows. I'll create a MWE.

**Comment by swaldhoer** [comment] 2023-04-06 12:05
So I used the [blinky example](https://github.com/ThrowTheSwitch/Ceedling/tree/1d783eba05072d9d0644a940e6b6c866b3cac735/examples/blinky) and just added

```yml
:flags:
  :test:
    :compile:
      :*:
        - -std=c99
```
and it works.

When I add the same lines in my project's ``project.yml`` it does not work.
I will need to have a closer look. Is there something known that could overwrite the settings (we are not using ``flags`` in our configuration file)?

Thanks for the fast reply.

**Comment by swaldhoer** [comment] 2023-04-06 12:49
Ok this is weird: once I remove ``use_test_preprocessor`` from the ``project`` settings, the flags are correctly passed.

Is this expected behavior?

**Comment by mkarlesky** [comment] 2023-07-22 14:43
@swaldhoer In the 0.32rc branch the core `:flags` handling behavior is now fixed with commit https://github.com/ThrowTheSwitch/Ceedling/commit/84528834bb0a45d167f0a02bec1ca442a6580ee4. I can't say what was happening in the code before the big refactoring for parallel task execution. I only know that `:flags:` were being processed, but, effectively, there were not actually applied to anything.

And, in fact, Ceedling never supported injecting test compilation flags (or any custom flags) into the preprocessor build steps. I am working on implementing that now. It's mostly complete, but this fix and new features will require thorough testing.

**Comment by luisGallet** [comment] 2023-07-24 18:35
@mkarlesky when will this be supported on an official ceedling release?

**Comment by mkarlesky** [comment] 2023-09-11 17:29
@luisGallet Technically, it's supported now. The new and improved `:flags` behavior is present in the 0.32 branch complemented by a fully revamped build structure that builds each test as a mini-project with its own defines, flags, and search paths. However, that branch is still pre-release, and there aren't yet much needed documentation updates.
