### ISSUE TITLE
ceedling throwing File.exists NoMethodError in Mac

### ISSUE THREAD

**Issue by chanduthedev** [ThrowTheSwitch/Ceedling#905] opened 2024-07-20 04:42 UTC
I installed ceedling using `gem install ceedling` and when I run  `ceedling version`, getting below error.
```
/usr/local/lib/ruby/gems/3.3.0/gems/ceedling-0.31.1/bin/ceedling:12:in `<top (required)>': undefined method `exists?' for class File (NoMethodError)

  project_found = File.exists?(main_filepath)
                      ^^^^^^^^
Did you mean?  exist?
	from /usr/local/lib/ruby/gems/3.3.0/bin/ceedling:25:in `load'
	from /usr/local/lib/ruby/gems/3.3.0/bin/ceedling:25:in `<main>'
```

**Ruby Version:** 
`ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-darwin22]`

**Gem Version:**
`gem -v
3.5.14`

**macOS:**
`macOs Ventura Version13.2.1`

**Comment by chanduthedev** [comment] 2024-07-20 07:53
Its working after downgrading my ruby version. 

**Ruby version:**
`ruby -v
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]`
**Gem Version:**
`gem -v
3.0.3.1`

**Ceedling Version:**
`ceedling version`
Welcome to Ceedling!
    Ceedling:: 0.31.1
       CMock:: 2.5.4
       Unity:: 2.5.4
  CException:: 1.3.3

**Comment by mvandervoord** [comment] 2024-07-20 12:06
It will also work if you upgrade to the release candidate. This bug has been fixed in the soon-to-be-released version.

**Comment by chanduthedev** [comment] 2024-07-20 14:01
May I know what you mean by `upgrade to the release candidate`? My apologies if it is very basic question.

I am getting below error when try to run very basic project to add two numbers.

`/Library/Ruby/Gems/2.6.0/gems/ceedling-0.31.1/lib/ceedling/configurator.rb:102:in `join': no implicit conversion of nil into String (TypeError)`

**Comment by mvandervoord** [comment] 2024-07-20 15:16
The problem is that new changes to Ruby broke the `0.31.x` versions of Ceedling. So this can be fixed by either rolling back to an earlier Ruby (as you did), or installing a release candidate of Ceedling.

- Open the [releases page](https://github.com/ThrowTheSwitch/Ceedling/releases) on github
- Expand the `Assets` of the latest release candidate. At this moment: [1.0.0-80cc9c4](https://github.com/ThrowTheSwitch/Ceedling/releases/tag/1.0.0-80cc9c4)
- Download the `*.gem` file
- In the folder that you downloaded to, open a command prompt
- Type `gem install --local ceedling-1.0.0-80cc9c4.gem` (or whatever the filename is)

If you had a previously installed version of Ceedling, likely this will now work. If you never installed Ceedling to this version of Ruby, then you probably have some dependencies to resolve like `gem install rake` for example.

If you run Ceedling as a gem and/or if you're working on a new project, you should be ready to go at this point.

If you have an existing project that installed Ceedling to a vendor folder, you'll need to upgrade the project. To do so (again from the command prompt): `ceedling upgrade <projectname>`

**Closed** 2024-07-27 01:46 UTC
