### ISSUE TITLE
Module generator not working

### ISSUE THREAD

**Issue by kevlut** [ThrowTheSwitch/Ceedling#375] opened 2019-08-06 14:46 UTC
Current installation:

```
  Ceedling:: 0.28.3
CException:: 1.3.1.18
     CMock:: 2.4.6.217
     Unity:: 2.4.3.122
```

Here are the last few lines of my `project.yaml`

```
:module_generator:
  :project_root: ./
  :source_root: ./
  :test_root: test/

:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - raw_output_report
```

No matter what I set `project_root` and `source_root` to, when I run `ceedling module:create[leds]` the .c and .h file are placed in `./src`.  No where else in my `project.yaml` is there a reference to ./src, so I'm not sure where its getting it from.

I also tried using different relative locations for `source_root` and that didn't help.  I also tried moving the entire `:module_generator:` below `:plugins:` and that didn't help.

Also, if you run `ceedling module:create[beacon]` twice, consecutively, an exception is throw.  I believe the documents imply that this should work, and that the source files that already exist won't be overwritten.

**Comment by dpostorivo** [comment] 2019-08-07 21:35
This is a duplicate of #291  has been resolved as of #365.

Also @mvandervoord any more updates on when the next release will be or what work is needed to get to that point?

**Closed** 2019-09-10 11:43 UTC
